# Main Configuration File
defaults:
  - model: gat
  - optimizer: adam
  - trainer: default
  - data: default
  - loss: weighted_mae
  - wandb: default
  - preprocessing: oligomer
  - _self_

# Experiment settings
seed: null  # Set to an integer for reproducibility
experiment_name: null  # Optional experiment name

# Further configuration that does not belong to any of the above groups
normalize_labels: minmax # False | minmax | standard

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

